language: node_js

node_js:
  - "0.10"
  - "0.11"

branches:
    only:
        - master
        - developer
        
before_script:
  - npm install -g bower
  - npm install -g grunt-cli
  - bower install
  - npm install

script:
  - grunt