(function(m){var b=jQuery,a="on",d="off";7>b.fn.jquery.split(".")[1]&&(a="bind",d="unbind");var e={version:"0.5.1a",event:{on:a,off:d},data:{cores:{},clss:{},plugins:{},imports:[]},config:{console:!0,createImport:!1,cls:{plugins:[]},imports:{cache:!1,path:"",parser:{jsborn:""}}},addEventListener:function(g,f,c){b(e)[e.event.on]("jsb."+g,{scope:c},f)},create:function(g,f,c){var a=e;a.config.createImport&&a._check_class(g);var d=a._get_class(g);if(!d)return a.echo("error","CLASS:NOT FIND",g),!1;if(d.config.abstr)return a.echo("error",
"CLASS:ABSTR",g),!1;d.config.nodes||(d.config.nodes=[]);if(d.config.single&&0<d.config.nodes.length)return a.echo("error","CLASS:SINGLE",g),!1;g=new d.cls(f);d.config.nodes.push(g);c||b(a).triggerHandler("jsb.create",g);return g},echo:function(b){if(console&&e.config.console)if(console[b])console[b](arguments);else e.echo("log","console no "+b+" method.")},extendCore:function(g,f){var c=g.split("."),a=f.config.name;if(e._get_core(a))return e.echo("log","Core: "+a+" already register."),e._get_core(a);
f.config=b.extend(f.config,{single:!0,abstr:!1,plugin:!1,core:!0});for(var d=0;d<c.length;d++){var h=h?h:m;if(d!=c.length-1)b.isEmptyObject(h[c[d]])&&(h[c[d]]={}),h=h[c[d]];else return h[c[d]]=e.create(a),e.data.cores[a]=h[c[d]],h[c[d]]}},extendPlugin:function(b,f){var c=f.config.name,a=e;if(a._get_plugin(c))return a.echo("log","Plugin: "+f+" already register."),a._get_plugin(c);a.data.plugins[c]={name:b,cls:f.cls};return a.data.plugins[c]},getClassData:function(){return e.data.clss},getImportData:function(){return e.data.imports},
importClass:function(a){var f="",c=!0;if(e._check_import(a))return!0;f=e._parser_url(a,".js");b.ajax({url:f,dataType:"script",cache:_j.config.imports.cache,async:!1,error:function(b,a,g){c=!1;e.echo("error","Require:"+f+" Message:"+g)},success:function(){e.data.imports.push({name:f,status:c})}});return c},removeEventListener:function(a){b(e).off("jsb."+a)},setConfig:function(a){return this.config=b.extend(!0,this.config,a)},_check_import:function(b){for(var a=0;a<e.data.imports.length;a++)if(e.data.imports[a].name==
b)return e.echo("log","same",e.data.imports[a],b),!0;return!1},_check_class:function(b){return this._get_class(b)?!0:this.importClass(b)},_get_core:function(b){return this.data.cores[b]?this.data.cores[b]:!1},_get_class:function(b){return this.data.clss[b]?this.data.clss[b]:!1},_get_plugin:function(b){return this.data.plugins[b]?this.data.plugins[b]:!1},_init:function(){this._init_oop()},_init_oop:function(){var a=this;a.cls=function(f,c){if(a._get_class(f))return a.echo("warn","CLASS:'"+f+"' define again"),
!0;var d=function(e){c.plugins=c.plugins?c.plugins:[];this._ary_extend=[];this._ary_template=[];this._ary_plugin=this._ary_plugin?this._ary_plugin:[];this._ary_plugin=b.merge(this._ary_plugin,c.plugins);this._ary_plugin=b.merge(this._ary_plugin,a.config.cls.plugins);var h=[];b.each(this._ary_plugin,function(a,c){-1==b.inArray(c,h)&&f!=c&&h.push(c)});this._ary_plugin=h;this.className=f;this._count=0;this._destroy=!1;this._plugin(d);this._extend(this);this._import();this.initialize(e);this.SUPER();
delete this._count;return!0};b.extend(d.prototype,a.cls.prototype,c);c.extend&&(a._check_class(c.extend),b.extend(d.prototype,a.cls.prototype,a._get_class(c.extend).cls.prototype,c));c.tpl&&_j._parser_tpl(c.tpl,f);c.css&&_j._parser_css(c.css,f);a.data.clss[f]={config:{name:f,single:c.single?!0:!1,abstr:c.abstr?!0:!1,plugin:!1,core:!1},cls:d};return a.data.clss[f]};a.cls.prototype={_plugin:function(b){if(b=this._ary_plugin)for(var c=0;c<b.length;c++)a._check_class(b[c]),this[a._get_plugin(b[c]).name]=
e.create(b[c],this)},_extend:function(b){var a=b.extend;a&&(this._ary_extend.push(b.extend),b=e._get_class(a).cls,b.prototype&&this._extend(b.prototype))},_import:function(){if(this.imports)for(var a=0;a<this.imports.length;a++){var c=this.imports[a];b.isEmptyObject(c)&&_j.echo("error","imports can't null");e._check_class(c)}},SUPER:function(){if(0<this._ary_extend.length&&this._count<this._ary_extend.length){var b=this._ary_extend[this._count];b&&(b=e._get_class(b).cls.prototype,this._count++,b._import(),
b.initialize.apply(this,arguments),b.extend&&this.SUPER())}},destroy:function(){if(this._destroy)return e.echo("error",this,"already destroy"),!0;for(var a=e._get_class(this.className),c=0;c<a.config.nodes.length;c++)a.config.nodes[c]==this&&a.config.nodes.splice(c,1);b(this).triggerHandler("cls.destroy",this);b(e).triggerHandler("jsb.destroy",this);this._destroy=!0;return this},addEventListener:function(a,c,d){b(this)[e.event.on]("cls."+a,{scope:d},c)},dispatchEvent:function(a,c){b(this).triggerHandler("cls."+
a,[this,c])},getTpl:function(a){a=a?"script#"+a:"";return b("head").find(a+'[jsb-tpl="'+this.className+'"]')},getCss:function(){return b("head").find('[jsb-css="'+this.className+'"]')},removeEventListener:function(a){b(this)[e.event.off]("cls."+a)},initialize:function(){}}},_parser_css:function(a,d){for(var c=b.isArray(a)?a:a.files,e=a.cache?a.cache:!1,k=a.async?a.async:!1,h=0;h<c.length;h++)b.ajax({type:"GET",cache:e,async:k,url:_j._parser_url(c[h]),success:function(a){var c=document.createElement("style");
b(c).attr("type","text/css");b(c).attr("jsb-css",d);c.styleSheet?c.styleSheet.cssText=a:c.innerHTML=a;b(c).appendTo("head")}})},_parser_tpl:function(a,d){for(var c=b.isArray(a)?a:a.files,e=a.cache?a.cache:!1,k=a.async?a.async:!1,h=0;h<c.length;h++)b.ajax({type:"GET",dataType:"html",cache:e,async:k,url:_j._parser_url(c[h]),success:function(a){a=b(a);a.attr("jsb-tpl",d);a.appendTo("head")}})},_parser_url:function(a,d){var c=_j.config.imports,e="",e=c.path;if(!b.isEmptyObject(c.parser)){var k=0;for(key in c.parser)if(a.match(RegExp("^"+
key,"g"))&&key.length>k)var h=c.parser[key],e=h.path?h.path:h,k=key.length}e=e+a+(d?d:"");h&&b.isFunction(h.parser)&&(e=h.parser.call(h,e));return e}};e._init();m.JSB=e;m.jsb||(m.jsb=e);m._j||(m._j=e)})(window);
(function(m){JSB.extendCore("JSB.core.model",JSB.cls("jsborn/cores/model",{initialize:function(){},getObjKey:function(b,a,d){var e=this,g=a.split("."),f=!1;d||(d=0);jQuery.each(b,function(c,l){c==g[d]&&(f=d<g.length-1?"object"===typeof b[c]?e.getObjKey(b[c],a,d+1):b[c]:b[c])});return f},getObjtDiff:function(b,a,d){this._ary_diff_check=[];b=this._check_obj_diff(b,a);return b[d]?b[d]:b},_check_obj_diff:function(b,a){var d=this;"undefined"===typeof b&&(b={});"undefined"===typeof a&&(a={});var e={},g=
{},f={};jQuery.each(a,function(a,l){var k=b[a];if("undefined"===typeof k)f[a]=l;else if(typeof k!=typeof l)g[a]=l;else if(k!==l)if("object"===typeof l){if(0<=jQuery.inArray(d._ary_diff_check,l))return!1;ret=d._check_obj_diff(k,l);jQuery.isEmptyObject(ret.modify)||(g[a]=jQuery.extend(!0,{},ret.modify));jQuery.isEmptyObject(ret.add)||(f[a]=jQuery.extend(!0,{},ret.add));jQuery.isEmptyObject(ret.del)||(e[a]=jQuery.extend(!0,{},ret.del));d._ary_diff_check.push(l)}else g[a]=l});jQuery.each(b,function(b,
d){"undefined"===typeof a[b]&&(e[b]=!0)});return{modify:g,add:f,del:e}}}))})(window);
(function(m){JSB.extendCore("JSB.core.channel",JSB.cls("jsborn/cores/channel",{addChannel:function(b){if(this.getChannel(b))return!1;this._obj_channel[b]={member:[]};return!0},delChannel:function(b){if(!this.getChannel(b))return!1;delete this._obj_channel[b];return!0},join:function(b,a,d){this.addChannel(b);this.getChannel(b).member.push(a);jQuery(this)[JSB.event.on](b,{scope:a},function(b){d.apply(a,arguments)});return!0},getChannel:function(b){return this._obj_channel[b]},getChannelData:function(){return this._obj_channel},
send:function(b){if(!this.getChannel(b))return!1;for(var a=[],d=1;d<arguments.length;d++)a.push(arguments[d]);jQuery(this).triggerHandler(b,a);return!0},leave:function(b,a){var d=jQuery._data(this,"events");if(!d[b])return!1;for(var e=0;e<d[b].length;e++)if(d[b][e].data.scope==a)return d[b].splice(e,1),!0;return!1},initialize:function(){var b=this;b._obj_channel={};JSB.addEventListener("destroy",function(a,d){for(x in b._obj_channel)b.leave(x,d)})}}))})(window);
(function(m){JSB.extendPlugin("model",JSB.cls("jsborn/plugins/model",{imports:["jsborn/cores/model"],initialize:function(b){var a=this;a.PLUG_MODEL={model:[]};a.parent=b?b:a;a.parent.addEventListener("destroy",function(){for(var b=0;b<a.PLUG_MODEL.model.length;b++)a.PLUG_MODEL.model[b].destroy()})},getModelData:function(b){return this.PLUG_MODEL.model},getModel:function(b){for(var a=0;a<this.PLUG_MODEL.model.length;a++){var d=this.PLUG_MODEL.model[a];if(d.getOption().key==b)return d}return!1},setModel:function(b,
a){var d=this.getModel(b);return d?d.change(a):!1},addModel:function(b,a){var d=JSB.create("jsborn/plugin/model/node",{key:b,data:jQuery.extend(!0,{},a)});this.PLUG_MODEL.model.push(d);return d},delModel:function(b){for(var a=0;a<this.PLUG_MODEL.model.length;a++){var d=this.PLUG_MODEL.model[a];if(d.getOption().key==b)return this.PLUG_MODEL.model.splice(a,1),d}return!1}}));JSB.cls("jsborn/plugin/model/node",{getData:function(){return jQuery.extend(!0,{},this._obj_data.data)},setData:function(b){this._obj_data.data=
b;return jQuery.extend(!0,{},this._obj_data.data)},setOption:function(b){return this._obj_data=b},getOption:function(){return this._obj_data},change:function(b){var a=JSB.core.model.getObjtDiff(this.getData(),b,"all");jQuery.isEmptyObject(a.add)||this.dispatchEvent("model-add",a.add);jQuery.isEmptyObject(a.del)||this.dispatchEvent("model-del",a.del);jQuery.isEmptyObject(a.modify)||this.dispatchEvent("model-modify",a.modify);return this.setData(b)},initialize:function(b){this.setOption(b)}})})(window);
(function(m){JSB.extendPlugin("dom",JSB.cls("jsborn/plugins/dom",{extend:"jsborn/plugins/model",initialize:function(b){var a=this;a.SUPER(a);a.PLUG_DOM={str_root:"body",tag:["INPUT","SELECT"],nodes:[]};a.parent=b?b:a;a.parent.addEventListener("destroy",function(){for(var b=0;b<a.PLUG_DOM.nodes.length;b++)a.PLUG_DOM.nodes[b].destroy()})},registerData:function(){var b=this;this.select().find("[jsb-data]").filter(function(){return!$(this).parentsUntil(b.select(),"[jsb-cls]").length}).each(function(a,
d){var e=jQuery(this),g=e.attr("jsb-data"),f=e.attr("jsb-data-event"),f=f?f.split(","):[],c=g.split(":"),g=c[0],l=c[1],k,c=b.PLUG_DOM;0>=f.length&&f.push("modify");k=-1==jQuery.inArray(e[0].tagName,c.tag)?"html":"val";for(a=0;a<f.length;a++)b.getModel(g)&&b.getModel(g).addEventListener("model-"+f[a],function(a,b,c){a=JSB.core.model.getObjKey(c,l);if(!1!==a)e[k](a)})})},registerClass:function(){var b=this;this.select().find("[jsb-cls]").filter(function(){return!$(this).parentsUntil(b.select(),"[jsb-cls]").length}).each(function(a,
d){var e=jQuery(this).attr("jsb-cls"),e=JSB.create(e);b.PLUG_DOM.nodes.push(e);jQuery(b).triggerHandler("cls.controller-create",[e,d])})},registerEvent:function(b){var a=this;this.select().find("[jsb-event]").filter(function(){return!$(this).parentsUntil(a.select(),"[jsb-cls]").length}).each(function(b,e){var g=jQuery(this).attr("jsb-event").split(":"),f=g[0],c=a.parent[g[1]];jQuery(this)[JSB.event.off](f)[JSB.event.on](f,{scope:a.parent},function(a){jQuery.isFunction(c)?c.apply(this,arguments):console.log("DOM IS NOT DEFINE EVENT CallBack",
b)})})},select:function(b){var a=this.PLUG_DOM.str_root;if(b)return jQuery(a).find(b);a||(a="body");return jQuery(a)},setRoot:function(b){this.PLUG_DOM.str_root=b;return this.PLUG_DOM.str_root},getRoot:function(){return this.PLUG_DOM.str_root}}))})(window);
