(function(k){var e=jQuery,l="on",m="off";7>e.fn.jquery.split(".")[1]&&(l="bind",m="unbind");var c={version:"0.5.1a",event:{on:l,off:m},data:{cores:{},clss:{},plugins:{},imports:[]},config:{console:!0,createImport:!1,cls:{plugins:[]},imports:{cache:!1,path:"",parser:{jsborn:""}}},addEventListener:function(a,d,b){e(c)[c.event.on]("jsb."+a,{scope:b},d)},create:function(a,d,b){var g=c;g.config.createImport&&g._check_class(a);var h=g._get_class(a);if(!h)return g.echo("error","CLASS:NOT FIND",a),!1;if(h.config.abstr)return g.echo("error",
"CLASS:ABSTR",a),!1;h.config.nodes||(h.config.nodes=[]);if(h.config.single&&0<h.config.nodes.length)return g.echo("error","CLASS:SINGLE",a),!1;a=new h.cls(d);h.config.nodes.push(a);b||e(g).triggerHandler("jsb.create",a);return a},echo:function(a){if(console&&c.config.console)if(console[a])console[a](arguments);else c.echo("log","console no "+a+" method.")},extendCore:function(a,d){var b=a.split("."),g=d.config.name;if(c._get_core(g))return c.echo("log","Core: "+g+" already register."),c._get_core(g);
d.config=e.extend(d.config,{single:!0,abstr:!1,plugin:!1,core:!0});for(var h=0;h<b.length;h++){var f=f?f:k;if(h!=b.length-1)e.isEmptyObject(f[b[h]])&&(f[b[h]]={}),f=f[b[h]];else return f[b[h]]=c.create(g),c.data.cores[g]=f[b[h]],f[b[h]]}},extendPlugin:function(a,d){var b=d.config.name,g=c;if(g._get_plugin(b))return g.echo("log","Plugin: "+d+" already register."),g._get_plugin(b);g.data.plugins[b]={name:a,cls:d.cls};return g.data.plugins[b]},getClassData:function(){return c.data.clss},getImportData:function(){return c.data.imports},
importClass:function(a){var d="",b=!0;if(c._check_import(a))return!0;d=c._parser_url(a,".js");e.ajax({url:d,dataType:"script",cache:_j.config.imports.cache,async:!1,error:function(a,e,f){b=!1;c.echo("error","Require:"+d+" Message:"+f)},success:function(){c.data.imports.push({name:d,status:b})}});return b},removeEventListener:function(a){e(c).off("jsb."+a)},setConfig:function(a){return this.config=e.extend(!0,this.config,a)},_check_import:function(a){for(var d=0;d<c.data.imports.length;d++)if(c.data.imports[d].name==
a)return c.echo("log","same",c.data.imports[d],a),!0;return!1},_check_class:function(a){return this._get_class(a)?!0:this.importClass(a)},_get_core:function(a){return this.data.cores[a]?this.data.cores[a]:!1},_get_class:function(a){return this.data.clss[a]?this.data.clss[a]:!1},_get_plugin:function(a){return this.data.plugins[a]?this.data.plugins[a]:!1},_init:function(){this._init_oop()},_init_oop:function(){var a=this;a.cls=function(d,b){if(a._get_class(d))return a.echo("warn","CLASS:'"+d+"' define again"),
!0;var g=function(c){b.plugins=b.plugins?b.plugins:[];this._ary_extend=[];this._ary_template=[];this._ary_plugin=this._ary_plugin?this._ary_plugin:[];this._ary_plugin=e.merge(this._ary_plugin,b.plugins);this._ary_plugin=e.merge(this._ary_plugin,a.config.cls.plugins);var f=[];e.each(this._ary_plugin,function(a,b){-1==e.inArray(b,f)&&d!=b&&f.push(b)});this._ary_plugin=f;this.className=d;this._count=0;this._destroy=!1;this._plugin(g);this._extend(this);this._import();this.initialize(c);this.SUPER();
delete this._count;return!0};e.extend(g.prototype,a.cls.prototype,b);b.extend&&(a._check_class(b.extend),e.extend(g.prototype,a.cls.prototype,a._get_class(b.extend).cls.prototype,b));b.tpl&&_j._parser_tpl(b.tpl,d);b.css&&_j._parser_css(b.css,d);a.data.clss[d]={config:{name:d,single:b.single?!0:!1,abstr:b.abstr?!0:!1,plugin:!1,core:!1},cls:g};return a.data.clss[d]};a.cls.prototype={_plugin:function(d){if(d=this._ary_plugin)for(var b=0;b<d.length;b++)a._check_class(d[b]),this[a._get_plugin(d[b]).name]=
c.create(d[b],this)},_extend:function(a){var b=a.extend;b&&(this._ary_extend.push(a.extend),a=c._get_class(b).cls,a.prototype&&this._extend(a.prototype))},_import:function(){if(this.imports)for(var a=0;a<this.imports.length;a++){var b=this.imports[a];e.isEmptyObject(b)&&_j.echo("error","imports can't null");c._check_class(b)}},SUPER:function(){if(0<this._ary_extend.length&&this._count<this._ary_extend.length){var a=this._ary_extend[this._count];a&&(a=c._get_class(a).cls.prototype,this._count++,a._import(),
a.initialize.apply(this,arguments),a.extend&&this.SUPER())}},destroy:function(){if(this._destroy)return c.echo("error",this,"already destroy"),!0;for(var a=c._get_class(this.className),b=0;b<a.config.nodes.length;b++)a.config.nodes[b]==this&&a.config.nodes.splice(b,1);e(this).triggerHandler("cls.destroy",this);e(c).triggerHandler("jsb.destroy",this);this._destroy=!0;return this},addEventListener:function(a,b,g){e(this)[c.event.on]("cls."+a,{scope:g},b)},dispatchEvent:function(a,b){e(this).triggerHandler("cls."+
a,[this,b])},getTpl:function(a){a=a?"script#"+a:"";return e("head").find(a+'[jsb-tpl="'+this.className+'"]')},getCss:function(){return e("head").find('[jsb-css="'+this.className+'"]')},removeEventListener:function(a){e(this)[c.event.off]("cls."+a)},initialize:function(){}}},_parser_css:function(a,d){for(var b=e.isArray(a)?a:a.files,g=a.cache?a.cache:!1,c=a.async?a.async:!1,f=0;f<b.length;f++)e.ajax({type:"GET",cache:g,async:c,url:_j._parser_url(b[f]),success:function(a){var b=document.createElement("style");
e(b).attr("type","text/css");e(b).attr("jsb-css",d);b.styleSheet?b.styleSheet.cssText=a:b.innerHTML=a;e(b).appendTo("head")}})},_parser_tpl:function(a,d){for(var b=e.isArray(a)?a:a.files,c=a.cache?a.cache:!1,h=a.async?a.async:!1,f=0;f<b.length;f++)e.ajax({type:"GET",dataType:"html",cache:c,async:h,url:_j._parser_url(b[f]),success:function(a){a=e(a);a.attr("jsb-tpl",d);a.appendTo("head")}})},_parser_url:function(a,d){var b=_j.config.imports,c="",c=b.path;if(!e.isEmptyObject(b.parser)){var h=0;for(key in b.parser)if(a.match(RegExp("^"+
key,"g"))&&key.length>h)var f=b.parser[key],c=f.path?f.path:f,h=key.length}c=c+a+(d?d:"");f&&e.isFunction(f.parser)&&(c=f.parser.call(f,c));return c}};c._init();k.JSB=c;k.jsb||(k.jsb=c);k._j||(k._j=c)})(window);
